import type { Metadata } from "next";
import localFont from "next/font/local";
import { Poppins } from 'next/font/google';
import { Crimson_Pro } from "next/font/google";
import "./globals.css";


export const poppins = Poppins({
  subsets: ['latin'], 
  weight: ['400', '600', '700'], 
  style: ['normal', 'italic'],
});

export const crisom_pro = Crimson_Pro({
  subsets: ['latin'], 
  weight: ['500'], 
  style: ['italic'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` ${poppins} bg-[#1E1E1E] h-screen`}>
        {children}
      </body>
    </html>
  );
}
